services:
  - type: web
    name: homonhon-inventory
    runtime: php
    plan: free
    region: singapore
    buildCommand: composer install
    startCommand: apache2-foreground
    envVars:
      - key: DB_HOST
        value: db.otrkginfndevnotgkajc.supabase.co
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: Wh01302016!2025
      - key: DB_PORT
        value: 5432
